### ISSUE TITLE
Can't exit with home menu

### ISSUE THREAD

**Issue by jupitteer** [Favna/FTP3DS#2]
On 11.4 n3ds with Luma 8.1. If I try to exit with the home menu and not having to press b than refresh, it says 'closing software' forever. I have to force restart.

**Comment by favna** [comment]
I have not made the code for FTPDB nor do I maintain it. FTPDB is merely a version of FTPD but build with the more generalized framework "Buildtools". For a more uptodate and maintained version you can use FTPD, which is what I based my project on. Please check if the issue also exists on FTPD and if it does make an issue on that repo. [link for repo](https://github.com/mtheall/ftpd)

That said, it probably is fixed on there based by looking at the latest commit.

**Comment by jupitteer** [comment]
The reason I use ftpdb is because it uses the n3ds' 804 mhz clockspeed. Does ftpd too?

**Comment by favna** [comment]
It does as can be seen here

![](http://i.imgur.com/PYQcqJL.jpg)

**Comment by meeeeeeeeeeeeeeee** [comment]
If it's a original nintendo 3ds you can turn off the wireless communication on the system when u close the and app it should Close. I have the same problem with the Youtube app on my 3ds so when it does that. I turn off the Wireless and turn it back on after the app closes.
